pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'oraclequote_azure:latest'

steps:
- script: docker build --no-cache -f Dockerfile -t $(ocir)/$(tenancy)/$(repo)/$(imageName) .
  displayName: 'Building Docker Image'

- script: |
    docker login https://$(ocir) -u $(dockerUser) -p "$(dockerPassword)"
    docker push $(ocir)/$(tenancy)/$(repo)/$(imageName)
  displayName: 'Sending Image to OCIR'

- script: |
    bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"

    mkdir /home/vsts/.kube
    echo '    apiVersion: v1' >> /home/vsts/.kube/config
    echo '    clusters:' >> /home/vsts/.kube/config
    echo '    - cluster:' >> /home/vsts/.kube/config
    echo '        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVRk84N0EyamNuTktLUGV3eFZpZDBtTnhPZGNnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNWVk14RGpBTUJnTlZCQWdUQlZSbGVHRnpNUTh3RFFZRFZRUUhFd1pCZFhOMAphVzR4RHpBTkJnTlZCQW9UQms5eVlXTnNaVEVNTUFvR0ExVUVDeE1EVDBSWU1ROHdEUVlEVlFRREV3WkxPRk1nClEwRXdIaGNOTWpBd05ERTVNREV4TkRBd1doY05NalV3TkRFNE1ERXhOREF3V2pCZU1Rc3dDUVlEVlFRR0V3SlYKVXpFT01Bd0dBMVVFQ0JNRlZHVjRZWE14RHpBTkJnTlZCQWNUQmtGMWMzUnBiakVQTUEwR0ExVUVDaE1HVDNKaApZMnhsTVF3d0NnWURWUVFMRXdOUFJGZ3hEekFOQmdOVkJBTVRCa3M0VXlCRFFUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOallqNXQ4UWg0VWwwQmIrVzJDK3E3eGFwZjU1eGhyMFFoUGVMblMKNkJ4OVR6dlNBbkxmOGhXR0gwUDBuWEdVT21rQUxFbEJQNzNIbzR1ekhmSW9VZlFLOTAwbitxKzlCb1B2eVhCMgp6eGF5aWFISlFGSUtDTUFZNFRyN1hRdjJaNEc3a252VTFTNEFPZnlHTFhSeG1uZUpHL0o0b2VydExRQmZ6NGxUCnRDeFBIY0MyeWp1RkRUcE9ZdndIMC9OZ25kR3VNSEZrMFNmQnBGMFFUbjNpajZzditvL2YxME1FOWkyMlZEcXEKK1VyZWZFSHZCSHRmZ0JQcnp1Mm9wMFZBS0xDWjFXeS94SXFJRnAxZWFZb2tuWC81NVZmOEVJY2V3T2xhdmpQZgo0MWRuMVRIMzZIT09MWTZ6OE5ndEFiNzFXNHJSWHE3aEdZQVp4ZXJoR2NEcGdBY0NBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUEJSVUU3MkxEd1IKNVFxZXhVWURndVI3dDJMU01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRFJjMGcwMHB5VVNRYUxOMG1QSjVMRgpuQkRqT0xIOVZDcStSMFZqRTNBc3Y5N05ZNW82QjY4UW91cVRuQ0JRcHNpNHZXVWZGSk9JVW1DVHFBZGhCN2puCjc4VDQ3c0dPdmtiNFFpSVBXZE5PQUZBdEFrNnZFWjdlTUZyMklNRXgwV2hmYVhUK2pva25oc0prc0R5YkpNeVkKUHZzWUFxWE9MNDhiVUhZVk1GOTFaeERaZEx1ZTF3emtnbUo2VTA5Z0RvWkd2Y2J0WEdRUmtBUU9lOGdNOGdDcgpUeFc1S0hvbTMxMW1nRUJLSGxqMjJYS1U1SloyRVpkZ2tyVXpyVHR4Zjdvb2x0WVp0eXkwNXlzY2ZXbk56NWNjCkR3VDB1cDk1S1dIZHB4ZXFINGJCZlU5dTM4ZjdVVmU3TkorZ2dTTGE5V0JxanErYzcyOXB2c2I4MHV4RGhJTWkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=' >> /home/vsts/.kube/config
    echo '        server: https://147.154.9.27:6443' >> /home/vsts/.kube/config
    echo '      name: cluster-c2tkm3egjrw' >> /home/vsts/.kube/config
    echo '    contexts:' >> /home/vsts/.kube/config
    echo '    - context:' >> /home/vsts/.kube/config
    echo '        cluster: cluster-c2tkm3egjrw' >> /home/vsts/.kube/config
    echo '        user: user-c2tkm3egjrw' >> /home/vsts/.kube/config
    echo '      name: context-c2tkm3egjrw' >> /home/vsts/.kube/config
    echo '    current-context: context-c2tkm3egjrw' >> /home/vsts/.kube/config
    echo '    kind: ""' >> /home/vsts/.kube/config
    echo '    users:' >> /home/vsts/.kube/config
    echo '    - name: user-c2tkm3egjrw' >> /home/vsts/.kube/config
    echo '      user:' >> /home/vsts/.kube/config
    echo '        exec:' >> /home/vsts/.kube/config
    echo '          apiVersion: client.authentication.k8s.io/v1beta1' >> /home/vsts/.kube/config
    echo '          args:' >> /home/vsts/.kube/config
    echo '          - ce' >> /home/vsts/.kube/config
    echo '          - cluster' >> /home/vsts/.kube/config
    echo '          - generate-token' >> /home/vsts/.kube/config
    echo '          - --cluster-id' >> /home/vsts/.kube/config
    echo '          - ocid1.cluster.oc1.iad.aaaaaaaaaezdonldgvtgiojrgq2gim3bgnrwcyjsgezdcnjzgc2tkm3egjrw' >> /home/vsts/.kube/config
    echo '          - --region' >> /home/vsts/.kube/config
    echo '          - us-ashburn-1' >> /home/vsts/.kube/config
    echo '          command: oci' >> /home/vsts/.kube/config
    echo '          env: []' >> /home/vsts/.kube/config

    mkdir /home/vsts/.oci
    echo '[DEFAULT]' >> /home/vsts/.oci/config
    echo 'user=ocid1.user.oc1..aaaaaaaat2tcthdxahoekkhnaaxtybu235pv42uvg4phwp6u7s6p7snhdnqq' >> /home/vsts/.oci/config
    echo 'fingerprint=3a:6e:91:fd:06:42:df:41:af:47:7a:d6:28:6b:e4:1f' >> /home/vsts/.oci/config
    echo 'key_file=/home/vsts/.oci/oci_api_key.pem' >> /home/vsts/.oci/config
    echo 'tenancy=ocid1.tenancy.oc1..aaaaaaaarmf64ufoolro2kzrupzyazqycjapqsyacn7rju64jyw4zbyb6j6q' >> /home/vsts/.oci/config
    echo 'region=us-ashburn-1' >> /home/vsts/.oci/config

    echo '-----BEGIN RSA PRIVATE KEY-----' >> /home/vsts/.oci/oci_api_key.pem
    echo 'MIIEpQIBAAKCAQEAvc9NUntgO/tfXOTyaaoDTaBXl40hwKB2AUVkis0JfXDlzbyz' >> /home/vsts/.oci/oci_api_key.pem
    printf 'DTuc2n7j+lcYgGF4U1o1w19TeOlDn4rZwGNJYtKCmbZlKRN3MTtI4DrDerP8VyNo' >> /home/vsts/.oci/oci_api_key.pem
    printf 'FZviOjxkD322xt7GzRB+BRUZM7s0ZjF78110F/qfpYZy3DXCs5ugSZ6YCrEjJ9gu' >> /home/vsts/.oci/oci_api_key.pem
    printf 'SQENN8CIEoftOtSUFyVKffdbYXZfIrEWV4DxWye0/J5Zp2RuezDoC/c5kY5ABWL9' >> /home/vsts/.oci/oci_api_key.pem
    printf '0KV+PSf4G/eqzezKzl5m71dxL0Qck4YG5yVegmrb1OCSpEzH/ce5Ainy5AGXI4aL' >> /home/vsts/.oci/oci_api_key.pem
    printf 'WCCvrhXLrDFikfYQuJYdO/dAfhn/zPn/kO9efQIDAQABAoIBAQCyh2uI6zam9FbL' >> /home/vsts/.oci/oci_api_key.pem
    printf '/yPrMtgMiYYZq8tVbRfRNj3NN/F3JVtg2d3n0mxELxmre4Q2LHeKnsz2yJCwp2bN' >> /home/vsts/.oci/oci_api_key.pem
    printf 'h0Is7LY31xy0C5S2v/JaQhLXpS38GZJ9O3ZI7OgqMmdDEtF52ExQ0PRXP3MG70vn' >> /home/vsts/.oci/oci_api_key.pem
    printf '2x9k1j+91iOXAxDCA2bwnK500FDdrAQ6sl6uEQgf5GOOSy1/MbLoZGnxuQgyhd0R' >> /home/vsts/.oci/oci_api_key.pem
    printf 'YvIjAhhb0wpDTtlIOFsmoiZmlGvWXEIm4NBkDc0VN7mQWPrBZ6vgVj8TOp3x7jEr' >> /home/vsts/.oci/oci_api_key.pem
    printf 'OBdJKA2H2fb8z2K9wGR9cdfB1eh3Aa6/oL36ktJJVB73ZpmP2/nOKXEUbmeQfBxM' >> /home/vsts/.oci/oci_api_key.pem
    printf 'mOr2l20ZAoGBAOKSJ6IF/TmEZDVNLGkGDMguZzOoyiWvgY7J/0zNCCjoTu9eNpTx' >> /home/vsts/.oci/oci_api_key.pem
    printf 'jD2/8KjuycNiqorWVlo/jWiM1srYaU4/PmDmky3wmYkcS0KwWr4DVN6nz+enON8D' >> /home/vsts/.oci/oci_api_key.pem
    printf 'MDjq4jf/IaKSj+85oGtvVuF1YVDjCFGzV3OJd24osJoyQPhqJR8cOeynAoGBANZ2' >> /home/vsts/.oci/oci_api_key.pem
    printf 'x8puOV3mlw65onelWvh2WLI2hOe0EvdnjcybJBsPiLwXHtjsOb0qZZPse/ftp1AA' >> /home/vsts/.oci/oci_api_key.pem
    printf '3SXq/UjmQumAxw3MSysA/mpEw0zy0aJBjbNic2tUg9FsNuqApZt3kovzxHPH9Ccj' >> /home/vsts/.oci/oci_api_key.pem
    printf '0abktOuurp1GPh4fxiKtjIri7+KHIzTqsCp9Ugw7AoGAcnygAkM8fb/kUvq4Iimo' >> /home/vsts/.oci/oci_api_key.pem
    printf 'c87e3z+/ReO1d82ib9B6+xDIMjRNKF4WG23N0c83rL9Cpf1AjUHn1pi0QLOyIpPa' >> /home/vsts/.oci/oci_api_key.pem
    printf 'lWRtop0dOCdP8Fbkw3czf38Uk13wYuBdkaU+wkTtXhTpHlzkLuWH5U1G63SNU5tn' >> /home/vsts/.oci/oci_api_key.pem
    printf '6T3hV4zAEGqsYdpg/6NnsakCgYEArNeZ+UmQLl9zCskNaUP45xnqLebGgj6csovg' >> /home/vsts/.oci/oci_api_key.pem
    printf 'ui+mj7CbUIuJruXjOtN6fhcvagc8uruXf8G9VA1PjATfZ/1n70ajxF2a0N85mH0g' >> /home/vsts/.oci/oci_api_key.pem
    printf 'iJwlzTCV9Cg0shXwYjWiA+z4PR+/Y/P4OXtFXFSyIcrEsV6GPtiD1kNDddvXwgQK' >> /home/vsts/.oci/oci_api_key.pem
    printf '6pOJlpUCgYEAr9G1JJQzp6YEAfp3UdrKijBTbfl0v2VOx3Yka6moF4IORODLQbfy' >> /home/vsts/.oci/oci_api_key.pem
    printf 'HnEOaDFPf060ef9HEGc3Ki0V1XcZucM7mGosh9ne29onzinExDLjIW2w7hzNcfbW' >> /home/vsts/.oci/oci_api_key.pem
    printf 'fyx0Ha+kGzMggoRO4oxwKDfzJ9N3YPuOp1aA3m9vI48cagBKTMD2lwc=' >> /home/vsts/.oci/oci_api_key.pem
    echo '-----END RSA PRIVATE KEY-----' >> /home/vsts/.oci/oci_api_key.pem

    kubectl config view
    kubectl get nodes
    kubectl replace -f ./callPDFReport/kubernetes.yaml --force
    sleep 120
    kubectl get services callpdfreport-service
    kubectl get pods
    kubectl describe pods