pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'oraclequote_azure:latest'

steps:
- script: |
    pwd
    docker build --no-cache -f Dockerfile -t $(ocir)/$(tenancy)/$(repo)/$(imageName) .
  displayName: 'Building Docker Image'

- script: |
    docker login https://$(ocir) -u $(dockerUser) -p "$(dockerPassword)"
    docker push $(ocir)/$(tenancy)/$(repo)/$(imageName)
  displayName: 'Sending Image to OCIR'

- script: |
    pip install oci-cli
    mkdir /home/vsts/.kube

    mkdir /home/vsts/.oci
    cd /home/vsts/.oci
    wget -O oci_api_key.pem https://www.dropbox.com/scl/fi/3yjruq1imww3nkzvgby4v/oci_api_key.pem?rlkey=60pu68fklor99ifbnr8jkfood&dl=0
    sudo chmod 600 /home/vsts/.oci/oci_api_key.pem

    echo '[DEFAULT]' > /home/vsts/.oci/config
    echo 'user=ocid1.user.oc1..aaaaaaaat2tcthdxahoekkhnaaxtybu235pv42uvg4phwp6u7s6p7snhdnqq' >> /home/vsts/.oci/config
    echo 'fingerprint=a0:6c:fe:9d:da:7b:fa:00:90:70:db:b6:2c:3f:4b:9d' >> /home/vsts/.oci/config
    echo 'key_file=/home/vsts/.oci/oci_api_key.pem' >> /home/vsts/.oci/config
    echo 'tenancy=ocid1.tenancy.oc1..aaaaaaaarmf64ufoolro2kzrupzyazqycjapqsyacn7rju64jyw4zbyb6j6q' >> /home/vsts/.oci/config
    echo 'region=us-ashburn-1' >> /home/vsts/.oci/config
    chmod 600 /home/vsts/.oci/config

    oci resource-manager job create-destroy-job --execution-plan-strategy AUTO_APPROVED --stack-id ocid1.ormstack.oc1.iad.amaaaaaaihuwreyaoaanscej56cowg2smdsrt5esdpz4uq7otrbyenyrnz7a

    oci ce cluster create-kubeconfig --cluster-id ocid1.cluster.oc1.iad.aaaaaaaa5bqos533gvotyizyukjfwyf4uvjtbl2vl7uf2llq2cl7fe57zvwa --file /home/vsts/.kube/config --region us-ashburn-1 --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT

    export KUBECONFIG=/home/vsts/.kube/config

    cd /home/vsts/work/1/s
    kubectl config view
    kubectl get nodes
    kubectl replace -f kubernetes.yaml --force
    sleep 120
    kubectl get services callpdfreport-service
    kubectl get pods
    kubectl describe pods
  displayName: 'Deploying to OKE and OCI Resource Manager'